services:

  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
     - opensearch
    environment:
      - OPENSEARCH_HOST=opensearch
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
    - discovery.type=single-node
    - plugins.security.disabled=true
    - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
    - "9200:9200"
    volumes:
    - opensearch-data:/usr/share/opensearch/data
volumes:
  opensearch-data:
networks:
  default:
    name: opensearch-net